/*
Navicat MySQL Data Transfer

Source Server         : koneksi
Source Server Version : 50621
Source Host           : localhost:3306
Source Database       : db_tibsc

Target Server Type    : MYSQL
Target Server Version : 50621
File Encoding         : 65001

Date: 2015-06-29 21:11:07
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `jawaban`
-- ----------------------------
DROP TABLE IF EXISTS `jawaban`;
CREATE TABLE `jawaban` (
  `id_kuesioner` int(11) DEFAULT NULL,
  `jawaban` varchar(255) DEFAULT NULL,
  `username` varchar(40) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of jawaban
-- ----------------------------
INSERT INTO `jawaban` VALUES ('1', 'C', null);
INSERT INTO `jawaban` VALUES ('2', 'B', null);
INSERT INTO `jawaban` VALUES ('3', 'C', null);
INSERT INTO `jawaban` VALUES ('4', 'A', null);
INSERT INTO `jawaban` VALUES ('5', 'C', null);
INSERT INTO `jawaban` VALUES ('6', 'B', null);
INSERT INTO `jawaban` VALUES ('7', 'B', null);
INSERT INTO `jawaban` VALUES ('8', 'B', null);
INSERT INTO `jawaban` VALUES ('9', 'A', null);
INSERT INTO `jawaban` VALUES ('10', 'B', null);
INSERT INTO `jawaban` VALUES ('11', 'A', null);
INSERT INTO `jawaban` VALUES ('12', 'D', null);
INSERT INTO `jawaban` VALUES ('13', 'B', null);
INSERT INTO `jawaban` VALUES ('14', 'C', null);
INSERT INTO `jawaban` VALUES ('15', 'B', null);
INSERT INTO `jawaban` VALUES ('16', 'C', null);
INSERT INTO `jawaban` VALUES ('17', 'D', null);
INSERT INTO `jawaban` VALUES ('18', 'E', null);
INSERT INTO `jawaban` VALUES ('19', 'E', null);
INSERT INTO `jawaban` VALUES ('20', 'B', null);
INSERT INTO `jawaban` VALUES ('21', 'C', null);
INSERT INTO `jawaban` VALUES ('22', 'D', null);
INSERT INTO `jawaban` VALUES ('23', 'D', null);
INSERT INTO `jawaban` VALUES ('24', 'C', null);
INSERT INTO `jawaban` VALUES ('25', 'B', null);
INSERT INTO `jawaban` VALUES ('26', 'D', null);
INSERT INTO `jawaban` VALUES ('27', 'B', null);
INSERT INTO `jawaban` VALUES ('28', 'C', null);
INSERT INTO `jawaban` VALUES ('29', 'C', null);
INSERT INTO `jawaban` VALUES ('30', 'A', null);
INSERT INTO `jawaban` VALUES ('31', 'D', null);
INSERT INTO `jawaban` VALUES ('32', 'C', null);
INSERT INTO `jawaban` VALUES ('33', 'C', null);
INSERT INTO `jawaban` VALUES ('34', 'D', null);
INSERT INTO `jawaban` VALUES ('35', 'A', null);
INSERT INTO `jawaban` VALUES ('36', 'A', null);
INSERT INTO `jawaban` VALUES ('37', 'C', null);
INSERT INTO `jawaban` VALUES ('38', 'B', null);
INSERT INTO `jawaban` VALUES ('39', 'D', null);
INSERT INTO `jawaban` VALUES ('40', 'D', null);
INSERT INTO `jawaban` VALUES ('41', 'E', null);
INSERT INTO `jawaban` VALUES ('42', 'C', null);
INSERT INTO `jawaban` VALUES ('43', 'C', null);
INSERT INTO `jawaban` VALUES ('44', 'A', null);
INSERT INTO `jawaban` VALUES ('45', 'C', null);
INSERT INTO `jawaban` VALUES ('46', 'C', null);
INSERT INTO `jawaban` VALUES ('47', 'A', null);
INSERT INTO `jawaban` VALUES ('48', 'C', null);
INSERT INTO `jawaban` VALUES ('49', 'B', null);
INSERT INTO `jawaban` VALUES ('50', 'D', null);
INSERT INTO `jawaban` VALUES ('51', 'B', null);
INSERT INTO `jawaban` VALUES ('52', 'B', null);
INSERT INTO `jawaban` VALUES ('53', 'C', null);
INSERT INTO `jawaban` VALUES ('54', 'E', null);
INSERT INTO `jawaban` VALUES ('55', 'E', null);
INSERT INTO `jawaban` VALUES ('56', 'C', null);
INSERT INTO `jawaban` VALUES ('57', 'D', null);
INSERT INTO `jawaban` VALUES ('58', 'C', null);
INSERT INTO `jawaban` VALUES ('59', 'D', null);
INSERT INTO `jawaban` VALUES ('60', 'E', null);
INSERT INTO `jawaban` VALUES ('61', 'B', null);
INSERT INTO `jawaban` VALUES ('62', 'B', null);
INSERT INTO `jawaban` VALUES ('63', 'B', null);
INSERT INTO `jawaban` VALUES ('64', 'C', null);
INSERT INTO `jawaban` VALUES ('65', 'D', null);
INSERT INTO `jawaban` VALUES ('66', 'D', null);

-- ----------------------------
-- Table structure for `tbdimensi`
-- ----------------------------
DROP TABLE IF EXISTS `tbdimensi`;
CREATE TABLE `tbdimensi` (
  `id_dimensi` int(11) NOT NULL AUTO_INCREMENT,
  `dimensi` varchar(50) DEFAULT NULL,
  `bobot` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_dimensi`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of tbdimensi
-- ----------------------------
INSERT INTO `tbdimensi` VALUES ('1', 'CORPORATE CONTRIBUTION', '3');
INSERT INTO `tbdimensi` VALUES ('2', 'STAKEHOLDER (USER) ORIENTATION', '4');
INSERT INTO `tbdimensi` VALUES ('3', 'OPERATIONAL EXCELLENCE (KEUNGGULAN OPERASIONAL) ', '4');
INSERT INTO `tbdimensi` VALUES ('4', 'FUTURE ORIENTATION (Orientasi Masa Depan)', '4');

-- ----------------------------
-- Table structure for `tbkuesioner`
-- ----------------------------
DROP TABLE IF EXISTS `tbkuesioner`;
CREATE TABLE `tbkuesioner` (
  `id_kuesioner` int(11) NOT NULL AUTO_INCREMENT,
  `pertanyaan` varchar(200) DEFAULT NULL,
  `id_dimensi` int(11) DEFAULT NULL,
  `variabel` varchar(50) DEFAULT NULL,
  `pila` varchar(200) DEFAULT NULL,
  `pilb` varchar(200) DEFAULT NULL,
  `pilc` varchar(200) DEFAULT NULL,
  `pild` varchar(200) DEFAULT NULL,
  `pile` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id_kuesioner`)
) ENGINE=InnoDB AUTO_INCREMENT=67 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of tbkuesioner
-- ----------------------------
INSERT INTO `tbkuesioner` VALUES ('1', 'Berapa persen kira-kira dana pengembangan TIK yang dialokasikan oleh kampus dari pengeluaran yang ada ?', '1', 'komitmen pimpinan', 'Dibawah 5%', 'Antara 5%-10%', 'Antara 11%-20%', 'Antara 21%-30%', 'Diatas 30%');
INSERT INTO `tbkuesioner` VALUES ('2', 'Apakah perguruan tinggi memiliki program sosialisasi dan edukasi mengenai pentingnya pemanfaatan TIK kampus?', '1', 'komitmen pimpinan', 'Ada, namun bersifat sporadis dan tidak terencana', 'Ada, dengan ruang lingkup dan target sasaran audience sesuai dengan anggaran', 'Ada, terencana dengan baik dilaksanakan secara konsisten, kontinyu dan berkesinambungan', 'Ada, terencana dengan baik dan dilaksanakan secara konsisten, kontinyu dan berkesinambungan dan mendapatkan banyak bantuan serta didukung dari stakeholder lain diluar perangkat organisasi perguruan', 'Ada, terencana dengan baik dan dilaksanakan secara konsisten, kontinyu dan berkesinambungan dan mendapatkan banyak bantuan serta didukung dari stakeholder lain diluar perangkat organisasi perguruan ti');
INSERT INTO `tbkuesioner` VALUES ('3', 'Apakah perguruan tinggi menggunakan media tertentu dalam melakukan sosialisasi dan edukasi mengenai pentingnya pemanfaatan teknologi informasi dan komunikasi kampus ?', '1', 'komitmen pimpinan', 'Tidak', 'Ya, di beberapa media namun dalam ukuran kecil', 'Ya, di sejumlah media dan cukup efektif', 'Ya, di sejumlah media dan sangat signifikan dampaknya', 'Ya, cukup banyak jalur media yang memberikan kontribusi positif dan signifikan terhadap perkembangan TIK perguruan tinggi.');
INSERT INTO `tbkuesioner` VALUES ('4', 'Dari manasajakah sumber dana terbesar yang diperuntukkan untuk melakukan investasi dalam membangun TIK Perguruan tinggi ?', '1', 'alokasi sumber daya', 'Tidak dari mana-mana, karena memang belum memiliki TIK', 'Diambil melalui dana yang berasal dari uang bayaran mahasiswa, baik yang berupa sumbangan maupun uang kuliah', 'Dialokasikan khusus oleh pemilik perguruan tinggi dalam bentuk belanja modal', 'Sebagian dari dana bantuan pemerintah Indonesia dan sisa hasil usaha penyelenggaraan belajar mengajar', 'Investasi pihak ketiga (eksternal) yang memiliki komitme penuh jangka panjang dalam membangun perguruan tinggi yang ada.');
INSERT INTO `tbkuesioner` VALUES ('5', 'Berapa kira-kira nilai investasi TIK dalam tiga tahun terakhir ?', '1', 'alokasi sumber daya', 'Kurang dari Rp. 100 juta', 'Rp. 100 â€“ 500 juta', 'Rp. 500 juta â€“ 1 Milyar', 'Rp. 1-3 Milyar', '> Rp. 3 Milyar');
INSERT INTO `tbkuesioner` VALUES ('6', 'Berapa jumlah karyawan yang berlatar belakang pendidikan perguruan tinggi bidang komputer atau informatika ?', '1', 'alokasi sumber daya', 'Kurang dari 1% dari keseluruhan pegawai di Perguruan tinggi', '2%-5% dari keseluruhan pegawai di Perguruan tinggi', '6%-15% dari keseluruhan pegawai di Perguruan tinggi', '16%-35% dari keseluruhan pegawai di Perguruan tinggi', '>35% dari keseluruhan pegawai di Perguruan tinggi');
INSERT INTO `tbkuesioner` VALUES ('7', 'Apakah perguruan tinggi memiliki unit unit atau divisi khusus yang bertanggung jawab terhadap perencanaan, pembangunan, penerapan, pengendalian  dan pengembangan TIK di lingkungan kampus ?', '1', 'unit pengelola teknologi', 'Tidak ada', 'Ada, namun tidak beroperasi secara optimal karena masih mengerjakan program atau proyek', 'Ada, dan merupakan suatu unit organisasi tersendiri dengan tanggung jawab yang jelas', 'Ada, merupakan suatu unit organisasi tersendiri, yang berjalan berdasarkan tanggung jawab yang jelas sesuai dengan SOP yang telah disusun dan dikembangkan', 'Ada, merupakan sebuah unit organisasi independen, dimana didukung oleh berbagai pihak ketiga yang sesuai dengan bidang keahliannya, dibawah tata kelola manajemen yang rapi dan transparan.');
INSERT INTO `tbkuesioner` VALUES ('8', 'Jika perguruan tinggi memiliki unit khusus yang dibentuk oleh pihak kampus untuk mengelola TIK yang dimiliki, dibawah komando siapa unit khusus ini berada ?', '1', 'unit pengelola teknologi', 'Tidak dibawah siapa-siapa, karena tidak terdapat unit yang dimaksud', 'Berada dibawah komando salah satu unit kegiatan yang ada di perguruan tinggi', 'Berada dibawah komando salah satu divisi kegiatan yang ada di perguruan tinggi', 'Berada dibawah komando salah satu wakil pimpinan perguruan tinggi institusi', 'Langsung dibawah komando pimpinan perguruan tinggi institusi');
INSERT INTO `tbkuesioner` VALUES ('9', 'Apakah perguruan tinggi memiliki unit atau divisi yang bertanggung jawab terhadap pelatihan TIK dalam lingkungan kampus ?', '1', 'unit pengelola teknologi', 'Tidak ada', 'Ada, namun tidak berorientasi secara optimal karena masih mengerjakan hal-hal yang bersifat ad-hoc, atau berbasis program atau proyek', 'Ada, dan merupakan suatu unit organisasi tersendiri dengan tanggung jawab yang jelas', 'Ada, merupakan suatu unit organisasi tersendiri, yang berjalan berdasarkan tanggung jawab yang jelas sesuai dengan SOP yang telah disusun dan dikembangkan.', 'Ada, merupakan sebuah unit organisasi independen, dimana didukung oleh berbagai pihak ketiga yang sesuai dengan bidang keahliannya, di bawah tata kelola manajemen yang rapi dan transparan');
INSERT INTO `tbkuesioner` VALUES ('10', 'Apakah perguruan tinggi memiliki kebijakan dan peraturan yang mengharuskan setiap civitas akademika memanfaatkan secara intensif TIK dalam lingkungan kampus sebagai penunjang kegiatan belajar mengajar', '1', 'kebijakan dan sistem insentif', 'Tidak memiliki', 'Tidak memiliki secara tertulis, namun sering disampaikan dan diwacanakan oleh segenap pimpinan', 'Terdapat kebijakan tertulis melalui surat keputusan pimpinan perguruan tinggi mengenai keharusan menggunakan TIK dalam lingkungan kampus.', 'Terdapat sejumlah kebijakan terkait dengan pemanfaatan TIK sesuai tata aturan yang ada, dan dijadikan sebagai salah satu pengukur kinerja unit maupun individu terkait', 'Terdapat berbagai kebijakan dan peraturan keharusan pemanfaatan TIK dalam lingkungan kampus dipergunakan sebagai komponen pengukur kinerja dan terdapat model insentif yang diterapkan manajemen kampus ');
INSERT INTO `tbkuesioner` VALUES ('11', 'Apakah ada sistem insentif yang dikembangkan oleh perguruan tinggi untuk mendorong agar segenap civitas akademika di kampus memanfaatkan teknologi informasi dan komunikasi seoptimal mungkin ?', '1', 'kebijakan dan sistem insentif', 'Tidak ada', 'Ada, namun tidak jelas dan konsisten penerapannya', 'Ada, dimana implementasinya diatur dalam peraturan perguruan tinggi', 'Ada, dimana implementasinya telah terintegrasi dengan sistem pengelolaan sumber daya manusia yang dimiliki oleh perguruan tinggi', 'Ada, dimana model dan implementasinya selain telah terintegrasi secara baik dengan sistem sumber daya manusia, tingkat efekivitasnya pun diukur dan dinilai dari hari ke hari.');
INSERT INTO `tbkuesioner` VALUES ('12', 'Bagaimana karyawan dan staf perguruan tinggi belajar mengenai cara memanfaatkan teknologi informasi dan komunikasi (missal : menggunakan computer dan internet) ?', '1', 'kebijakan dan sistem insentif', 'Kebanyakan belajar sendiri (mandiri) atau otodidak', 'Kebanyakan belajar dari orang lain dan sumber referensi (buku)', 'Kebanyakan belajar dari orang lain, sumber referensi dan mengikuti pendidikan non formal (pelatihan dan kursus)', 'Kebanyakan belajar dari orang lain, sumber referensi dan mengikuti pendidikan formal dan vokasi', 'Kebanyakan belajar dari orang lain, sumber referensi, mengikuti pendidikan formal (akademik maupun vokasi) maupun informal.');
INSERT INTO `tbkuesioner` VALUES ('13', 'Bagaimana karyawan dan staf perguruan tinggi belajar mengenai cara memanfaatkan teknologi informasi dan komunikasi (misal : menggunakan komputer dan internet) ?', '1', 'kebijakan dan sistem insentif', 'Kebanyakan belajar sendiri (mandiri) atau otodidak', 'Kebanyakan belajar dari orang lain dan sumber referensi (buku)', 'Kebanyakan belajar dari orang lain, sumber referensi dan mengikuti pendidikan non formal (pelatihan dan kursus)', 'Kebanyakan belajar dari orang lain, sumber referensi dan mengikuti pendidikan formal dan vokasi', 'Kebanyakan belajar dari orang lain, sumber referensi, mengikuti pendidikan formal (akademik maupun vokasi) maupun informal');
INSERT INTO `tbkuesioner` VALUES ('14', 'Apakah perguruan tinggi telah memiliki dan menyusun Rencana Strategis Pengembangan TIK (IT Master Plan) untuk kebutuhan kampus ?', '1', 'Renstra dan peta jalan', 'Tidak memiliki', 'Memiliki, namun sudah lama tidak dimutakhirkan (update)', 'Memiliki dan setiap tahun diperbaharui', 'Memiliki dan secara konsisten seluruh program pengembangan TIK kampus didasari pada dokumen ini.', 'Memiliki dan secara konsisten seluruh program pengembangan TIK kampus didasari pada dokumen ini dan dilakukan audit terhadap efektivitas kepatuhannya.');
INSERT INTO `tbkuesioner` VALUES ('15', 'Apakah Rencana Strategis Pengembangan TIK (IT Master Plan) yang dimiliki dipergunakan sebagai panduan / acuan dalam menyelenggarakan berbagai proyek kegiatan teknologi informasi dan komunikasi perguru', '1', 'Renstra dan peta jalan', 'Tidak karena memang belum memiliki Rencana Strategis Pengembangan IT (IT Master Plan)', 'Ya, namun baru sebagian kecil saja proyek atau kegiatan yang mengacu pada dokumen ini.', 'Ya, rata-rata proyek atau kegiatan mengacu pada dokumen ini', 'Ya, sebagian besar proyek atau kegiatan mengacu pada dokumen ini.', 'Ya, semua proyek mengacu pada dokumen ini, jika ada proyek yang tidak termasuk maka menjadi bahan masukan untuk merevisi dokumen yang ada.');
INSERT INTO `tbkuesioner` VALUES ('16', 'Bagaimana cara perguruan tinggi menyusun kebutuhan teknologi informasi dan komunikasi yang diinginkan ? ', '1', 'Perencanaan dan pengorganisasian', 'Berkaca pada perguruan tinggi lain, dan mencoba mengikutinya.', 'Menyusun kebutuhan TIK berdasarkan keinginan orang yang menangani TIK', 'Menyusun kebutuhan TIK berdasarkan jumlah unit-unit yang membutuhkan TIK', 'Menyusun kebutuhan TIK berdasarkan analisis kebutuhan masing-masing unit', 'Menyusun kebutuhan TIK berdasarkan analisis kebutuhan masing-masing unit dan senantiasa diperbaharui dan dimutakhirkan sesuai perkembangan organisasi.');
INSERT INTO `tbkuesioner` VALUES ('17', 'Apakah perguruan tinggi memiliki dokumen arsitektur yang dipergunakan sebagai panduan atau acuan teknis pembangunan teknologi informasi dan komunikasi di perguruan tinggi ?', '1', 'Perencanaan dan pengorganisasian', 'Tidak memiliki', 'Ya, namun sebagian kecil inisiatif pembangunan teknologi informasi dan komunikasi yang mengadu pada rancangan arsitektur ini', 'Ya, rata-rata inisiatif pembangunan teknologi informasi dan komunikasi mengacu pada rancangan arsitektur ini.', 'Ya, sebagian besar inisiatif pembangunan teknologi informasi dan komunikasi mengacu pada rancangan arsitektur ini', 'Ya, semua inisiatif pembangunan teknologi informasi dan komunikasi mengacu pada rancangan arsitektur ini.');
INSERT INTO `tbkuesioner` VALUES ('18', 'Apakah perguruan tinggi anda memiliki standar terkait teknologi informasi dan komunikasi di perguruan tinggi yang akan diadopsi (missal : standar dalam tipe aplikasi, fitur / spesifikasi piranti keras', '1', 'Perencanaan dan pengorganisasian', 'Tidak ada sama sekali', 'Ada, kadang-kadang dipergunakan, kadang-kadang tidak', 'Ada, dipergunakan secara konsisten sebagai basis pengelolaan dan dikembangkan secara kontinyu dan berkesinambungan', 'Ada, dipergunakan secraa konsisten sebagai basis pengelolaan dan dikembangkan secara kontinyu dan berkesinambungan', 'Ada, dipergunakan secara konsisten sebagai basis pengelolaan, dikembangkan secara kontinyu dan berkesinambungan, dan dievaluasi / diaudit kepatuhan adopsinya');
INSERT INTO `tbkuesioner` VALUES ('19', 'Apakah memiliki mekanisme penghitungan cost benefit dari setiap program, atau inisiatif investasi pengembangan teknologi informasi dan komunikasi di perguruan tinggi ?', '1', 'Perencanaan dan pengorganisasian', 'Tidak ada, namun sudah dipikirkan untuk menyusunnya', 'Ada, namun belum secara konsisten diadopsi sepenuhnya', 'Ada, dan dijadikan sebagai acuan baku pelaksanaan manajemen proyek teknologi informasi', 'Ada, dipergunakan sebagai acuan baku pelaksanaan manajemen proyek teknologi informasi dan dijadikan basis evaluasi kinerja perangkat organisasi perguruan tinggi', 'Ada, dipergunakan sebagai acuan baku pelaksanaan manajemen proyek teknologi informasi dan dijadikan basis evaluasi kinerja perguruan tinggi dan senantiasa dikembangkan / direvisi mekanisme baku yang d');
INSERT INTO `tbkuesioner` VALUES ('20', 'Apakah segenap pimpinan perguruan tinggi secara intensif menggunakan beragam aplikasi teknologi informasi dan komunikasi dalam aktivitas sehari-harinya ?', '1', 'Pengadaan dan penerapan ', 'Tidak sama sekali', 'Ya, menggunakan namun tidak optimal dan tidak intensif', 'Ya, menggunakan secara efektif dan cukup intensif', 'Ya. menggunakan secara sangat intensif, efektif dan optimal', 'Ya, menggunakan secara sangat intensif, efektif, optimal dan telah berhasil menularkan kebiasaan ini kepada segenap pimpinan manajerial di bawahnya');
INSERT INTO `tbkuesioner` VALUES ('21', 'Apakah suasana atau budaya memanfaatkan teknologi informasi dan komunikasi terasa di dalam lingkungan kampus ?', '1', 'Pengadaan dan penerapan', 'Tidak sama sekali', 'Cukup terasa namun dalam keadaan atau waktu-waktu tertentu saja', 'Cukup terasa dalam situasi sehari-hari', 'Ya, sangat terasa karena hampir seluruh lokasi strategis Nampak segenap civitas akademika memanfaatkan teknologi', 'Ya, sangat terasa karena secara massif terlihat dari aktivitas segenap civitas akademika yang berinteraksi dengan teknologi di setiap sudut-sudut kampus');
INSERT INTO `tbkuesioner` VALUES ('22', 'Apakah perguruan tinggi memiliki dokumen yang jelas dan detail (misal : standar operasional prosedur) dari proses pengelolaan teknologi informasi dan komunikasi di perguruan tinggi ?', '1', 'Pengelolaan dan pengembangan', 'Tidak ada, semua berjalan seperti kebiasaan saja', 'Tidak ada, semua berjalan seperti kebiasaan saja', 'Ada, dipergunakan sebagai panduan kerja namun tidak pernah dikaji maupun dimutakhirkan', 'Ada, dipergunakan sebagai panduan kerja senantiasa dimutakhirkan sesuai dengan perbaikan dan dipakai sebagai basis evaluasi kinerja', 'Ada, dipergunakan sebagai panduan kerja senantiasa dimutakhirkan sesuai dengan perbaikan dan dipakai sebagai basis evaluasi kinerja dan penentuan remunerasi berdasarkan beban kerja dan tanggung jawab');
INSERT INTO `tbkuesioner` VALUES ('23', 'Apakah memiliki standar baku dalam manajemen pengelolaan proyek (project management) teknologi informasi dan komunikasi di perguruan tinggi ?', '1', 'Pengelolaan dan pengembangan', 'Tidak ada, namun sudah dipikirkan untuk menyusunnya', 'Ada, namun belum secara konsisten diadopsi sepenuhnya', 'Ada, dan dijadikan acuan baku pelaksanaan manajemen proyek teknologi informasi dan dijadikan basis evaluasi kinerja perangkat organisasi perguruan tinggi', 'Ada, dipergunakan sebagai acuan baku pelaksanaan manajemen proyek teknologi informasi dan dijadikan basis kinerja perangkan organisasi perguruan tinggi', 'Ada, dipergunakan sebagai acuan baku pelaksanaan manajemen proyek teknologi informasi dan dijadikan basis kinerja perangkan organisasi perguruan tinggi dan senantiasa dikembangkan / direvisi mekanisme');
INSERT INTO `tbkuesioner` VALUES ('24', 'Apakah perguruan tinggi anda memiliki prosedur penanganan keadaan darurat (contingency plan) bila terjadi gangguan pada sistem teknologi informasi dan komunikasi ?', '1', 'Pengelolaan dan pengembangan', 'Tidak ada, semua berjalan secara naluri dan kebiasaan saja', 'Ada, dipergunakan sebagai panduan kerja namun tidak pernah dikaji dan dimutakhirkan', 'Ada, dipergunakan sebagai panduan kerja, senantiasa dimutakhirkan sesuai dengan perbaikan', 'Ada, dipergunakan sebagai panduan kerja, senantiasa dimutakhirkan sesuai dengan perbaikan, dan dipakai sebagai basis evaluasi kinerja', 'Ada, dipergunakan sebagai panduan kerja, senantiasa dimutakhirkan sesuai dengan perbaikan, dan dipakai sebagai basis evaluasi kinerja serta penentuan remunerasi berdasarkan beban kerja dan tanggung ja');
INSERT INTO `tbkuesioner` VALUES ('25', 'Apakah tersedia pelayanan “help desk” untuk membantu para pengguna teknologi informasi dan komunikasi yang memiliki masalah ?', '1', 'Pengelolaan dan pengembangan', 'Tidak tersedia', 'Tersedia, namun kinerjanya tidak seperti yang diharapkan', 'Tersedia dan beroperasi dengan baik pada jam kerja', 'Tersedia dan beroperasi dengan baik selama 24 jam sehari, kecuali hari libur atau Sabtu / Minggu', 'Tersedia dan beroperasi dengan baik selama 24 jam sehari, dan tujuh hari seminggu');
INSERT INTO `tbkuesioner` VALUES ('26', 'Apakah dilakukan proses audit terhadap efektivitas penerapan teknologi informasi dan komunikasi di lingkungan kampus ?', '1', 'Pemantauan dan penilaian', 'Tidak sama sekali', 'Pada dasarnya dilakukan evaluasi secara umum, namun tidak berdasarkan prosedur baku audit', 'Ya, dilakukan audit oleh pihak internal yang berkepentingan dan memiliki kapabilitas', 'Ya, dilakukan audit oleh pihak eksternal yang berkepentingan dan memiliki kapabilitas', 'Ya, dilakukan audit oleh pihak internal dan eksternal secara independen dan bertanggung jawab');
INSERT INTO `tbkuesioner` VALUES ('27', 'Apakah perguruan tinggi memiliki indikator kinerja utama (Key Performance Indicator) dalam implementasi teknologi informasi dan komunikasi kampus ?', '1', 'Pemantauan dan penilaian', 'Tidak ada, semuanya berjalan secara naluri dan kebiasaan', 'Ada, dipergunakan sebagai panduan kerja, namun tidak pernah dikaji maupun dimutakhirkan', 'Ada, dipergunakan sebagai panduan kerja, senantiasa dimutakhirkan sesuai dengan perbaikan', 'Ada, dipergunakan sebagai panduan kerja, senantiasa dimutakhirkan sesuai dengan perbaikan dan dipakai sebagai basis evaluasi kinerja', 'Ada, dipergunakan sebagai panduan kerja, senantiasa dimutakhirkan sesuai dengan perbaikan dan dipakai sebagai basis evaluasi kinerja dan penentuan remunerasi berdasarkan beban kerja dan tanggung jawab');
INSERT INTO `tbkuesioner` VALUES ('28', 'Berapa persen kira-kira materi perkuliahan yang telah berbentuk file elektronik atau digital ?', '2', 'Dosen dan peneliti', 'Dibawah 10%', 'Kira-kira antara 11%-25%', 'Kira-kira antara 26%-50%', 'Kira-kira antara 51%-75%', 'Kira-kira diatas 76%');
INSERT INTO `tbkuesioner` VALUES ('29', 'Berapa persen kira-kira materi perkuliahan yang dibawakan oleh dosen telah memanfaatkan dan melibatkan teknologi informasi dan komunikasi untuk mempermudah pemahaman mahasiswa sebagai peserta ajar ?', '2', 'Dosen dan peneliti', 'Dibawah 10%', 'Kira-kira antara 11%-25%', 'Kira-kira antara 26%-50%', 'Kira-kira antara 51%-75%', 'Kira-kira diatas 76%');
INSERT INTO `tbkuesioner` VALUES ('30', 'Berapa persen kira-kira jumlah mata kuliah yang telah dilakukan dengan menggunakan metode e-learning ?', '2', 'Dosen dan peneliti', 'Tidak ada sama sekali', 'Kira-kira dibawah 10%', 'Kira-kira antara 11%-25%', 'Kira-kira antara 26%-50%', 'Kira-kira diatas 50%');
INSERT INTO `tbkuesioner` VALUES ('31', 'Berapa persen kira-kira jumlah mata kuliah dimana sang dosen memberikan pekerjaan rumah yang memaksa mahasiswanya untuk menggunakan teknologi informasi dan komunikasi secara intensif ?', '2', 'Dosen dan peneliti', 'Tidak ada sama sekali', 'Kira-kira dibawah 10%', 'Kira-kira dibawah 10%', 'Kira-kira antara 26%-50%', 'Kira-kira diatas 50%');
INSERT INTO `tbkuesioner` VALUES ('32', 'Bagaimana tingkat literasi dosen dalam memanfaatkan berbagai aplikasi teknologi informasi dan komunikasi ?', '2', 'Dosen dan peneliti', 'Rata-rata sangat rendah, karena kebanyakan masih gagap teknologi', 'Rata-rata cukup mahir menggunakan komputer, hanya saja kebanyakan diperuntukkan dalam mendukung kegiatan administratif (mengetik, mengirim email, membuat tabulasi, dan lain-lain)', 'Rata-rata cukup mahir dan menguasai berbagai aplikasi standar yang dipergunakan oleh seorang pengajar untuk mendukung aktivitasnya sehari-hari', 'Kebanyakan dosen telah sangat mahir dalam menggunakan beragam aplikasi standar maupun aplikasi termutakhir yang dikenal masyarakat umum', 'Mayoritas dosen telah sangat mahir dalam menggunakan beragam aplikasi standar maupun aplikasi termutakhir yang dikenal masyarakat umum, bahkan cenderung lebih tinggi tingkat  literasinya dibandingkan ');
INSERT INTO `tbkuesioner` VALUES ('33', 'Apakah terjadi komunikasi yang intens antara dosen dan mahasiswa melalui kanal dan aplikasi teknologi informasi dan komunikasi seperti email, mailing list, newsgroup, social networking dan lain-lain ?', '2', 'Dosen dan peneliti', 'Tidak sama sekali', 'Terjadi komunikasi virtual, namun tidak terlampau intensif', 'Terjadi komunikasi virtual yang cukup intensif', 'Hampir setiap hari rata-rata mahasiswa dan dosen melakukan interaksi secara virtual', 'Setiap hari mayoritas mahasiswa dan dosen melakukan interaksi secara virtual');
INSERT INTO `tbkuesioner` VALUES ('34', 'Berapa jumlah kelas yang pada saat diselenggarakan sang dosen membentuk sebuah mailing list khusus untuk para mahasiswa yang mengambil mata kuliah yang bersangkutan ?', '2', 'Dosen dan peneliti', 'Dibawah 5% dari total kelas yang diikuti mahasiswa selama masa kuliah', 'Kira-kira antara 6%-15% dari total kelas yang diikuti mahasiswa selama masa kuliah', 'Kira-kira antara 16%-30% dari total kelas yang diikuti mahasiswa selama masa kuliah', 'Kira-kira antara 31%-60% dari total kelas yang diikuti mahasiswa selama masa kuliah', 'Diatas 6%-15% dari total kelas yang diikuti mahasiswa selama masa kuliah');
INSERT INTO `tbkuesioner` VALUES ('35', 'Berapa persen dari dosen yang memiliki alamat email yang aktif dipergunakan?', '2', 'Dosen dan peneliti', 'Dibawah 10%', 'Kira-kira antara 11%-20%', 'Kira-kira antara 21%-50%', 'Kira-kira antara 51%-75%', 'Diatas antara 75%');
INSERT INTO `tbkuesioner` VALUES ('36', 'Berapa persen dari dosen yang memiliki website / homepage atau blog pribadi?', '2', 'Dosen dan peneliti', 'Dibawah 10%', 'Kira-kira antara 11%-20%', 'Kira-kira antara 21%-50%', 'Kira-kira antara 51%-75%', 'Diatas antara 75%');
INSERT INTO `tbkuesioner` VALUES ('37', 'Rata-rata berapa jam dalam sehari seorang dosen berinteraksi dengan internet?', '2', 'Dosen dan peneliti', 'Hanya dibawah 1 jam per hari', 'Kurang lebih antara 1-2 jam per hari', 'Kurang lebih antara 2-4 jam per hari', 'Kurang lebih antara 4-6 jam per hari', 'Hampir diatas 6 jam per hari');
INSERT INTO `tbkuesioner` VALUES ('38', 'Berapa persen dari mahasiswa yang memiliki alamat email yang aktif dipergunakan ?', '2', 'Mahasiswa, unsur pemilik dan pimpinan', 'Dibawah 10%', 'Kira-kira antara 11%-20%', 'Kira-kira antara 21%-50%', 'Kira-kira antara 51%-75%', 'Diatas antara 75%');
INSERT INTO `tbkuesioner` VALUES ('39', 'Rata-rata berapa jam dalam sehari seorang mahasiswa berinteraksi dengan internet ?', '2', 'Mahasiswa, unsur pemilik dan pimpinan', 'Hanya dibawah 1 jam per hari', 'Kurang lebih antara 1-2 jam per hari', 'Kurang lebih antara 2-4 jam per hari', 'Kurang lebih antara 4-6 jam per hari', 'Hampir diatas 6 jam per hari');
INSERT INTO `tbkuesioner` VALUES ('40', 'Berapa persen dari karyawan yang memiliki alamat email yang aktif dipergunakan ?', '2', 'Manajemen, staf dan karyawan', 'Dibawah 10%', 'Kira-kira antara 11%-20%', 'Kira-kira antara 21%-50%', 'Kira-kira antara 51%-75%', 'Diatas antara 75%');
INSERT INTO `tbkuesioner` VALUES ('41', 'Bagaimana tingkat literasi karyawan dalam memanfaatkan berbagai aplikasi teknologi informasi dan komunikasi untuk membantu kegiatan administratif dan operasional kampus ?', '2', 'Manajemen, staf dan karyawan', 'Rata-rata sangat rendah, karena kebanyakan masih “gagap teknologi”', 'Rata-rata cukup mahir menggunakan satu atau dua aplikasi komputer', 'Rata-rata cukup mahir dan menguasai sejumlah aplikasi komputer untuk kegiatan operasional organisasi', 'Kebanyakan karyawan telah mahir dan menguasai dan menggunakan berbagai aplikasi komputer perkantoran maupun penunjang lainnya', 'Mayoritas karyawan sangat mahir dalam memanfaatkan dan menggunakan beraneka ragam aplikasi teknologi dan komunikasi');
INSERT INTO `tbkuesioner` VALUES ('42', 'Apakah anda merasa keberadaan teknologi infomasi dan komunikasi akan memberikan manfaat dan kontribusi signifikan bagi perkembangan perguruan tinggi anda ?', '3', 'Peningkatan kualitas', 'Ya, keberadaannya akan memberikan kontribusi positif namun tidak signifikan', 'Ya, keberadaannya akan memberikan kontribusi positif, namun signifikan tidaknya bergantung dari sudut pandang yang dipergunakan', 'Ya keberadaan akan memberikan kontribusi positif dan signifikan bagi perguruan tinggi ', 'Ya keberadaan akan memberikan kontribusi positif dan signifikan bagi perguruan tinggi bahkan dapat meningkatkan daya saing jika direncanakan dan diterapkan dengan benar', 'Ya keberadaan akan memberikan kontribusi positif dan signifikan bagi perguruan tinggi dan sanggup mentransformasikan situasi dan kondisi perguruan tinggi ke arah modernisasi kampus');
INSERT INTO `tbkuesioner` VALUES ('43', 'Apakah ada kontribusi nyata terkait dengan teknologi informasi dan komunikasi dalam hal peningkata kualitas pengambilan keputusan para pembuat kebijakan di perguruan tinggi anda dalam 5 tahun terakhir', '3', 'Peningkatan kualitas', 'Tidak ada kontribusi yang signifikan', 'Ada sejumlah kontribusi positif, namun tidak signifikan', 'Ada kontribusi positif dan cukup signifikan', 'Jelas terlihat adanya kontribusi yang positif dan signifikan serta dapat diukur besaran peningkatannya', 'Jelas terlihat adanya kontribusi yang positif dan signifikan dapat diukur besaran peningkatannya dan memberikan manfaat langsung bagi para mahasiswa');
INSERT INTO `tbkuesioner` VALUES ('44', 'Apakah ada kontribusi nyata terkait dengan teknologi informasi dan komunikasi dalam hal peningkatan kualitas pelayanan di kalangan para mahasiswa di perguruan tinggi anda dalam 5 tahun terakhir ?', '3', 'Peningkatan kualitas', 'Tidak ada kontribusi yang signifikan', 'Ada sejumlah kontribusi positif, namun tidak signifikan', 'Ada kontribusi positif dan cukup signifikan', 'Jelas terlihat adanya kontribusi yang positif dan signifikan serta dapat diukur besaran peningkatannya', 'Jelas terlihat adanya kontribusi yang positif dan signifikan, dapat diukur besaran peningkatannya dan memberikan manfaat langsung bagi para mahasiswa/i');
INSERT INTO `tbkuesioner` VALUES ('45', 'Apakah ada kontribusi teknologi informasi dan komunikasi dalam hal peningkatan peran perguruan tinggi dalam konteks nasional dalam 5 taun terakhir ?', '3', 'Peningkatan kualitas', 'Tidak ada kontribusi yang signifikan', 'Ada kontribusi positif, namun tidak signifikan', 'Ada kontribusi positif dan cukup signifikan', 'Jelas terlihat adanya kontribusi yang positif dan signifikan serta dapat diukur besaran peningkatannya', 'Jelas terlihat adanya kontribusi yang positif dan signifikan, dapat diukur besaran peningkatannya dan memberikan manfaat langsung bagi pemerintah');
INSERT INTO `tbkuesioner` VALUES ('46', 'Apakah pernah mendapatkan penghargaan dari lembaga-lembaga lain, dari luar maupun dalam negeri terkait dengan perkembangan teknologi informasi dan komunikasi di perguruan tinggi anda ?', '3', 'Peningkatan kualitas', 'Pernah, memperoleh 1 penghargaan dalam 10 tahun terakhir', 'Pernah, memperoleh 2-3 penghargaan dalam 10 tahun terakhir', 'Pernah, memperoleh 4-5 penghargaan dalam 10 tahun terakhir', 'Pernah, memperoleh 6-10 penghargaan dalam 10 tahun terakhir', 'Pernah, memperoleh lebih dari 10 penghargaan dalam 10 tahun terakhir');
INSERT INTO `tbkuesioner` VALUES ('47', 'Apakah ada kontribusi nyata terkait dengan teknologi informasi dan komunikasi dalam hal peningkatan kualitas pengetahuan dan kompetensi mahasiswa/i di berbagai jurusan dalam 5 tahun terakhir ?', '3', 'Peningkatan kualitas', 'Tidak ada kontribusi yang signifikan', 'Ada sejumlah kontribusi positif, namun tidak signifikan', 'Ada kontribusi positif dan cukup signifikan', 'Jelas terlihat adanya kontribusi yang positif dan signifikan serta dapat diukur besaran peningkatannya', 'Jelas terlihat adanya kontribusi yang positif dan signifikan, dapat diukur besaran peningkatannya dan memberikan manfaat langsung bagi mahasiswa/i');
INSERT INTO `tbkuesioner` VALUES ('48', 'Apakah ada kontribusi nyata terkait teknologi informasi dan komunikasi dalam hal peningkatan kualitas pengetahuan dan kompetensi mahasiswa/i dari berbagai jurusan di perguruan tingg anda dalam 5 tahun', '3', 'Peningkatan kualitas', 'Tidak ada kontribusi yang signifikan', 'Ada sejumlah kontribusi positif, namun tidak signifikan', 'Ada kontribusi positif dan cukup signifikan', 'Jelas terlihat adanya kontribusi yang positif dan signifikan serta dapat diukur besaran peningkatannya', 'Jelas terlihat adanya kontribusi yang positif dan signifikan, dapat diukur besaran peningkatannya dan memberikan manfaat langsung bagi mahasiswa/i');
INSERT INTO `tbkuesioner` VALUES ('49', 'Apakah ada kontribusi nyata terkait teknologi informasi dan komunikasi dalam hal peningkatan, efisiensi operasional penyelenggaraan perguruan tinggi anda dalam 5 tahun terakhir ?', '3', 'Efektivitas dan efisiensi', 'Tidak ada kontribusi yang signifikan', 'Ada sejumlah kontribusi positif, namun tidak signifikan', 'Ada kontribusi positif dan cukup signifikan', 'Jelas terlihat adanya kontribusi yang positif dan signifikan serta dapat diukur besaran peningkatannya', 'Jelas terlihat adanya kontribusi yang positif dan signifikan, dapat diukur besaran peningkatannya dan memberikan manfaat langsung bagi perguruan tinggi');
INSERT INTO `tbkuesioner` VALUES ('50', 'Apakah ada kontribusi nyata terkait teknologi informasi dan komunikasi dalam hal peningkatan pendapatan perguruan tinggi dalam 5 tahun terakhir ?', '3', 'Efektivitas dan efisiensi', 'Tidak ada kontribusi yang signifikan', 'Ada sejumlah kontribusi positif, namun tidak signifikan', 'Ada kontribusi positif dan cukup signifikan', 'Jelas terlihat adanya kontribusi yang positif dan signifikan serta dapat diukur besaran peningkatannya', 'Jelas terlihat adanya kontribusi yang positif dan signifikan, dapat diukur besaran peningkatannya dan memberikan manfaat langsung bagi perguruan tinggi');
INSERT INTO `tbkuesioner` VALUES ('51', 'Apakah ada kontribusi nyata terkait teknologi informasi dan komunikasi dalam hal perbaikan pegawai perguruan tinggi yang bersih, akuntabel dan transparan dalam 5 tahun terakhir ?', '3', 'Transparansi manajemen', 'Tidak ada kontribusi yang signifikan', 'Ada sejumlah kontribusi positif, namun tidak signifikan', 'Ada kontribusi positif dan cukup signifikan', 'Jelas terlihat adanya kontribusi yang positif dan signifikan serta dapat diukur besaran peningkatannya', 'Jelas terlihat adanya kontribusi yang positif dan signifikan, dapat diukur besaran peningkatannya dan memberikan manfaat langsung bagi manajemen');
INSERT INTO `tbkuesioner` VALUES ('52', 'Apakah ada kontribusi nyata terkait teknologi informasi dan komunikasi dalam hal peningkatan optimalisasi pemanfaatan berbagai sumber daya yang dimiliki perguruan tinggi anda dalam 5 tahun terakhir ?', '3', 'Utilitas sumber daya', 'Tidak ada kontribusi yang signifikan', 'Ada sejumlah kontribusi positif, namun tidak signifikan', 'Ada kontribusi positif dan cukup signifikan', 'Jelas terlihat adanya kontribusi yang positif dan signifikan serta dapat diukur besaran peningkatannya', 'Jelas terlihat adanya kontribusi yang positif dan signifikan, dapat diukur besaran peningkatannya dan memberikan manfaat langsung bagi perguruan tinggi');
INSERT INTO `tbkuesioner` VALUES ('53', 'Menurut pendapat anda, apa peranan dan target utama penerapan teknologi informasi dan komunikasi di perguruan tinggi anda ?', '3', 'Transformasi organisasi', 'Memfasilitas proses komunikasi dan diseminasi informasi agar lebih cepat', 'Memfasilitas proses komunikasi dan diseminasi informasi agar lebih cepat serta meningkatkan kerja operasional pelayanan', 'Memfasilitas proses komunikasi dan diseminasi informasi agar lebih cepat serta meningkatkan kerja operasional pelayanan dan membantu proses pengambilan keputusan yang efektif', 'Memfasilitas proses komunikasi dan diseminasi informasi agar lebih cepat, meningkatkan kerja operasional pelayanan, membantu proses pengambilan keputusan yang efektif dan memastikan terjadinya proses ', 'Memfasilitas proses komunikasi dan diseminasi informasi agar lebih cepat, meningkatkan kerja operasional pelayanan, membantu proses pengambilan keputusan yang efektif dan memastikan terjadinya proses ');
INSERT INTO `tbkuesioner` VALUES ('54', 'Apakah kebijakan perguruan tinggi memperbolehkan penyelenggaraan mata kuliah berbasis e-learing ?', '4', 'Implementasi e-learning', 'Tidak diperbolehkan sama sekali', 'Diperbolehkan, namun tetap harus dicampur denga model pembelajaran klasik (tatap muka)', 'Diperbolehkan sesuai dengan peraturan Kemdiknas / Dikti yang ada', 'Diperbolehkan bahkan dianjurkan untuk dilaksanakan oleh segenap dosen pengajar', 'Diperbolehkan bahkan  dianjurkan untuk sejumlah dosen melaksanakan sesuai dengan pengembangan yang direncanakan');
INSERT INTO `tbkuesioner` VALUES ('55', 'Apakah pimpinan memberikan himbauan akan pentingnya antara dosen pengajar saling berbagi pakai (sharing) materi perkuliahan dan pengetahuan yang dimilikinya ?', '4', 'Berbagai sumber daya', 'Tidak diberikan himbauan', 'Diberikan himbauan secara informal', 'Secara resmi pimpinan senantiasa memberikan himbauan tersebut dalam berbagai kesempatan formal', 'Terdapat surat keputusan dari pihak pimpinan yang mengharuskan para dosen untuk saling berbagi pengetahuan dan materi ajar yang dimilikinya', 'Terdapat surat keputusan dari pihak pimpinan yang mengharuskan para dosen untuk saling berbagi pengetahuan dan materi ajar yang dimilikinya dan dijadikan alat ukur kinerja dosen');
INSERT INTO `tbkuesioner` VALUES ('56', 'Apakah perguruan tinggi anda menyediakan fasilitas teknologi untuk menunjang proses berbagi materi ajar antar dosen?', '4', 'Berbagai sumber daya', 'Ya, namun jarang sekali dipergunakan oleh dosen', 'Ya, namun hanya beberapa dosen saja yang aktif berbagi materi ajar', 'Ya dan rata-rata dosen saling berbagi materi ajar antar sesamanya', 'Ya dan kira-kira lebih dari 50% telah secara aktif saling berbagi materi ahar', 'Ya hampir semua dosen saling aktif berbagi materi ajar diantara sesamanya');
INSERT INTO `tbkuesioner` VALUES ('57', 'Berapa banyak yang mengunjungi website perguruan tinggi sehari-hari (per idetitas unik) ?', '4', 'Berbagai sumber daya', 'Mungkin kira-kira dibawah 100 hits per hari', 'Kira-kira antara 101 – 1000 hits per hari', 'Kira-kira antara 1001 – 10.000 hits per hari', 'Kira-kira antara 10.001 – 100.000 hits per hari', 'Diatas 100.000 hits per hari');
INSERT INTO `tbkuesioner` VALUES ('58', 'Berdasarkan rekam jejak, fitur website perguruan tinggi apa yang paling banyak dimanfaatkan oleh pengunjung ?', '4', 'Berbagai sumber daya', 'Tidak jelas, karena tidak ada catatannya', 'Fitur navigasi umum untuk mencari informasi', 'Fitur navigasi umum untuk mencari informasi dan berinteraksi dengan pihak perguruan tinggi', 'Fitur “searching “ untuk mencari dan mengunduh dokumen / artikel penting yang dimiliki perguruan tinggi', 'Fitur aplikasi yang menungkinkan pengunjung untuk turut berpartisipasi dalam berbagai program perguruan tinggi berbasis virtual (e-learning, webcast, knowledge simulationm smart campus dan lain-lain)');
INSERT INTO `tbkuesioner` VALUES ('59', 'Apakah pimpinan menganjurkan agar para dosen mengunggah berbagai hasil karyanya ke internet ?', '4', 'Pendidikan terbuka', 'Tidak menganjurkan sama sekali', 'Menganjurkan hanya untuk artikel tertentu saja', 'Menganjurkan untuk semua karya yang dimiliki dengan tetap memperhatikan unsur HAKI yang dimiliki', 'Mengharuskan para dosen untuk sebanyak mungkin meng-upload hasil karyanya ke internet', 'Mengharuskan para dosen untuk sebanyak mungkin meng-upload hasil karyanya ke internet dan dijadikan sebagai bagian dari penilaian kinerja dosen');
INSERT INTO `tbkuesioner` VALUES ('60', 'Apakah pimpinan dan segenap dosen perguruan tinggi mengetahui akan adanya model HAKI bernama “creative common” ?', '4', 'Pendidikan terbuka', 'Tidak mengetahui sama sekali', 'Pernah mendengar, namun tidak tahu persis artinya', 'Tahu mengenai keberadaannya dan mengerti maksudnya', 'Tahu mengenai keberadaannya, mengerti maksudnya dan telah dipergunakan sejumlah dosen perguruan tinggi', 'Tahu mengenai keberadaannya, mengerti maksudnya dan secara masif telah dipergunakan sejumlah dosen perguruan tinggi');
INSERT INTO `tbkuesioner` VALUES ('61', 'Berapa banyak materi perkuliahan dosen yang diberikan secara terbuka dan gratis kepada publik ', '4', 'Pendidikan terbuka', 'Tidak ada sama sekali', 'Dibawah 10% dari total mata kuliah', 'Kira-kira antara 11%-25% dari total mata kuliah', 'Kira-kira antara 26%-50% dari total mata kuliah', 'Diatas 50% dari total mata kuliah');
INSERT INTO `tbkuesioner` VALUES ('62', 'Apakah perguruan tinggi menjadi salah satu penggiat atau peserta forum / asosiasi Open Course Ware (OCW)', '4', 'Pendidikan terbuka', 'Tidak ada sama sekali', 'Berencana untuk menjadi anggotanya dalam waktu dekat', 'Menjadi penggiat dan anggota aktif dari perkumpulan Open Course Ware (OCW)', 'Menjadi penggiat dan anggota aktif dan sekaligus pengurus Open Course Ware (OCW) di sejumlah tempat', 'Menjadi inisiator sekaligus pemimpin gerakan Open Course Ware (OCW) di sejumlah wilayah');
INSERT INTO `tbkuesioner` VALUES ('63', 'Bagaimana model pengelolaan sistem informasi internal terkait dengan kewajiban melaporkan status kampus melalui sistem informasi PDPT (Pangkalan Data Perguruan Tinggi) ?', '4', 'Pangkalan data terpadu', 'Perguruan tinggi tidak memiliki sistem informasi internal', 'Keduanya merupakan sistem yang berdiri sendiri, tidak berhubungan', 'Sistem informasi dirancang sedemikian rupa sehingga menghasilkan output sebagaimana format file PDPT', 'Dikti dapat secara langsung mengambil file (mengunduh) dari hasil keluaran sistem informasi internal yang formatnya sesuai dengan PDPT melalui website perguruan tinggi', 'Kedua sistem sudah terintegrasi');
INSERT INTO `tbkuesioner` VALUES ('64', 'Apakah sistem informasi akademik perguruan tinggi dapat diakses melalui website oleh pihak luar ?', '4', 'Pangkalan data terpadu', 'Tidak dapat sama sekali', 'Dapat diakses hanya untuk dosen atau mahasiswa aktif (alumni) perguruan tinggi', 'Dapat diakses oleh berbagai pihak sesuai dengan hak otoritasnya masing-masing', 'Dapat diakses oleh berbagai pihak yang membutuhkan data/informasi mengenai dosen, mahasiswa, mata kuliah, materi ajar, pustaka internal dan lain-lain, dimana sistem mencatat keseluruhan model interaks', 'Dapat diakses oleh berbagai pihak luar untuk mendapatkan informasi / data yang dibutuhkan disamping itu dapat dilakukan berbagai query atau searching terhadap kumpulan basis data yang dimiliki perguru');
INSERT INTO `tbkuesioner` VALUES ('65', 'Apakah perguruan tinggi memiliki jejaring ke institusi pendidikan atau penelitian lain di luar negeri ?', '4', 'Jejaring internasional', 'Tidak ada', 'Sedang menjajaki kerjasama dengan pihak luar negeri', 'Memiliki jejaring ke sejumlah lembaga atau institusi lain di luar negeri', 'Memiliki jejaring ke sejumlah institusi lain di luar negeri yang memungkinkan dosen untuk saling mengakses sumber-sumber pembelajaran dari pihak mitra', 'Memiliki jejaring ke sejumlah institusi lain di luar negeri yang memungkinkan dosen dan mahasiswa untuk saling mengakses sumber-sumber pembelajaran dari pihak mitra');
INSERT INTO `tbkuesioner` VALUES ('66', 'Apakah perguruan tinggi anda mendapatkan dukungan dan bantuan sumber daya maupun asistensi dari pihak ketiga (lembaga internasional) yang berasal dari luar negeri ?', '4', 'Jejaring internasional', 'Tidak ada', 'Ada, namun sangat jarang sekali (satu dalam 3-5 tahun)', 'Ada, namun berupa bantuan kecil paling tidak setahun sekali', 'Ada, jumlah bantuannya cukup besar dan diterima secara berkesinambungan', 'Ada, jumlah bantuannya besar dan diterima secara kontinyu serta berkesinambungan');

-- ----------------------------
-- Table structure for `tbpengguna`
-- ----------------------------
DROP TABLE IF EXISTS `tbpengguna`;
CREATE TABLE `tbpengguna` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(150) NOT NULL,
  `password` varchar(150) NOT NULL,
  `hak_akses` varchar(100) NOT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of tbpengguna
-- ----------------------------
INSERT INTO `tbpengguna` VALUES ('4', 'admin', 'admin', 'administrator');
INSERT INTO `tbpengguna` VALUES ('5', 'alec', 'alec', 'dekan');
INSERT INTO `tbpengguna` VALUES ('6', 'sandy', 'sandy', 'kepala puskom');
